"""Sphinx configuration for the QMaterialise documentation.

This file contains only the most minimal configuration to build the
documentation.  See the Sphinx documentation for all available
options: https://www.sphinx-doc.org/en/master/usage/configuration.html
"""

import os
import sys
from datetime import datetime

# Add the project source directory to sys.path so that autodoc can
# import the package.
sys.path.insert(0, os.path.abspath(os.path.join('..', 'src')))

# General information about the project.
project = 'Q-Materialise'
author = 'Lewis'
copyright = f"{datetime.now().year}, {author}"

# The master toctree document.
master_doc = 'index'

# List of Sphinx extensions enabled for this documentation.  You can add
# more extensions here if you need advanced features such as
# intersphinx or todo lists.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.autodoc.typehints',
]

# The language for content autogenerated by Sphinx.  Refer to
# documentation for a list of supported languages.
language = 'en'

# The style to use for HTML and HTML Help pages.  We'll use the
# built‑in alabaster style for simplicity.
html_style = 'alabaster'

# Paths that contain templates, relative to this directory.
templates_path = ['_templates']

# Patterns to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# Output file base name for HTML help builder.
htmlhelp_basename = 'QtMaterialPlusDoc'