"""
Sphinx configuration for the Q-Materialise documentation.

This file contains only the most minimal configuration to build the
Alabaster-themed documentation. See the Sphinx documentation for all
available options:
https://www.sphinx-doc.org/en/master/usage/configuration.html
"""

import sys
from pathlib import Path
from datetime import datetime

# -- Path setup --------------------------------------------------------------
# Add the project source directory to sys.path for autodoc to find the package
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

# -- Project information -----------------------------------------------------
project = "Q-Materialise"
author = "Lewis (Arched dev)"
copyright = f"{datetime.now().year}, {author}"
# The root document (formerly master_doc)
root_doc = "index"

# -- General configuration ---------------------------------------------------
# Sphinx extensions
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.autodoc.typehints",
]

# Render type hints in the description rather than signature
autodoc_typehints = "description"

# Paths that contain templates
templates_path = ["_templates"]
# Files and directories to ignore
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# Language for autogenerated content
language = "en"

# -- Options for HTML output -------------------------------------------------
# Use the Alabaster theme
html_theme = "alabaster"
# If you have custom static files (e.g., style sheets), use this
html_static_path = ["_static"]

# Base name for HTML help builder
htmlhelp_basename = "QMaterialiseDoc"
